name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4  # Checkout the code from the repository
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up Django environment
      run: |
        # Make sure Django is running from the correct directory
        cd finance_news  # Navigate to your Django project folder
        python manage.py migrate  # Apply migrations if necessary
    - name: Run Tests
      run: |
        cd finance_news  # Navigate to your Django project folder
        python manage.py test  # Run Django tests
